version: "3.8"

services:
  hell-yeah-bot-pg:
    image: postgres
    volumes:
      - hell-yeah-bot-pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$PG_DB
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PASS
    ports:
      - $PG_PORT:5432

volumes:
  hell-yeah-bot-pg-data:
    name: hell-yeah-bot-pg-data
